spring:
  application:
    name: elastic-query-web-client
  profiles:
    include: elastic_query_web_client
  config:
    import: 'configserver:'
  cloud:
    config:
      name: elastic-query-web-client,config-client
      username: spring_cloud_user
      password: '{cipher}73617456b40fc6064d8e86958db8c2f387d226860767fd50ffaa67f175f75cb7b24396dd04469845eaaffd1e2679e76f'

encrypt:
  key: springCloud!2020