twitter-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  welcome-message: Hello microservices world!
  enable-mock-tweets: false
  mock-min-tweet-length: 5
  mock-max-tweet-length: 10
  mock-sleep-ms: 1000
