spring:
  application:
    name: reactive-elastic-query-service
  profiles:
    include: reactive_elastic_query
  config:
    import: 'configserver:'
  cloud:
    config:
      name: reactive-elastic-query-service,config-client
      username: spring_cloud_user
      password: '{cipher}73617456b40fc6064d8e86958db8c2f387d226860767fd50ffaa67f175f75cb7b24396dd04469845eaaffd1e2679e76f'

encrypt:
  key: springCloud!2020